# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: Safeguard Privilaged Sessions Integration Pool

steps:
  - script: |
      plugintool link-test-data
      pipenv install -d
      pipenv run pluginv run-tests
    displayName: 'Run a multi-line script'
